from __future__ import annotations

from .models import KeywordCategory

_THERAPY_PLAIN = [
    "therapeutic",
    "physical therapy",
    "active therapy",
    "occupational therapy",
    "speech therapy",
    "aquatic therapy",
    "vestibular",
    "vestibular rehabilitation therapy",
    "neurocognitive therapy",
    "neurocognitive rehabilitation",
    "cognitive rehabilitation therapy",
    "chiropractic",
    "manipulation",
    "reeducation",
]
_THERAPY_CODES = [
    "97110",
    "97112",
    "97140",
    "97162",
    "97163",
    "97164",
    "97530",
    "G0283",
    "97014",
    "97012",
]

CATEGORY_THERAPY = KeywordCategory(
    name="THERAPY",
    keywords=_THERAPY_PLAIN
    + _THERAPY_CODES
    + [
        "PT",
        "OT",
        "VRT",
        "CRT",
        "ST",
        "dry needling",
        "massage therapy",
        "myofascial",
        "ultrasound therapy",
        "electrical stimulation",
        "TENS",
        "exercise therapy",
        "range of motion",
        "ROM",
        "strengthening",
        "stretching",
        "home exercise program",
        "HEP",
        "work hardening",
        "work conditioning",
        "functional capacity evaluation",
        "FCE",
        "rehabilitation",
        "rehab",
    ],
    patterns=[
        r"(?<!\d)971\d\d(?!\d)",
        r"(?<!\d)972\d\d(?!\d)",
        r"\bG02\d\d\b",
        r"\b(hot|cold)\s+pack\b",
        r"\belectrical\s+stim(?:ulation)?\b",
    ],
    weight=1.5,
)

CATEGORY_MEDICAL_TREATMENT = KeywordCategory(
    name="MEDICAL_TREATMENT",
    keywords=[
        "prognosis",
        "medication",
        "dosage",
        "referral",
        "follow-up",
        "follow up",
        "chief complaint",
        "history of present illness",
        "HPI",
        "review of systems",
        "ROS",
        "physical examination",
        "impression",
        "clinical summary",
        "discharge summary",
        "discharge instructions",
        "inpatient",
        "outpatient",
        "emergency department",
        "urgent care",
        "clinical note",
        "progress note",
        "SOAP note",
        "subjective",
        "objective",
        "presenting complaint",
        "patient complaint",
        "office visit",
        "consultation",
        "consult",
        "discharge prescription",
        "post-operative order",
        "postoperative order",
    ],
    patterns=[
        r"\b[A-Z]\d{2}(?:\.\d{1,4})?\b",
    ],
    weight=2.5,
)

CATEGORY_BILLING = KeywordCategory(
    name="BILLING",
    keywords=[
        # Standard billing identifiers
        "date of service",
        "DOS",
        "date of injury",
        "DOI",
        "claim number",
        "claim no",
        "invoice",
        "statement",
        "account number",
        "insurance",
        "insurer",
        "payer",
        "policyholder",
        "member ID",
        "group number",
        "authorization",
        "pre-authorization",
        "referral number",
        "EOB",
        "explanation of benefits",
        "explanation of payment",
        "EOP",
        "EOMB",
        "remittance",
        "ERA",
        "CMS-1500",
        "UB-04",
        "superbill",
        "charge",
        "billed amount",
        "allowed amount",
        "paid amount",
        "adjustment",
        "balance due",
        "copay",
        "coinsurance",
        "deductible",
        "unit",
        "modifier",
        "place of service",
        "POS",
        "NPI",
        "TIN",
        "tax ID",
        "total price",
        "billed",
        "unit price",
        "balance",
        "receipt",
        "payment",
        "fee",
        "CPT",
        "ICD",
        "HCPCS",
        "visit code",
        # Hospital / facility billing
        "itemized statement",
        "itemized bill",
        "itemized charges",
        "revenue code",
        "rev code",
        "DRG",
        "APR-DRG",
        "total charges",
        "amount due",
        "patient responsibility",
        "patient portion",
        "outstanding balance",
        "prior balance",
        "contractual adjustment",
        "contractual allowance",
        "write-off",
        "network discount",
        "not covered",
        # Provider identification
        "rendering provider",
        "referring provider",
        "ordering provider",
        "billing provider",
        "subscriber ID",
        "subscriber name",
        "insured ID",
        "group name",
        "plan name",
        # Government payers
        "Medicare",
        "Medicaid",
        "Medi-Cal",
        "Medicare part A",
        "Medicare part B",
        "Medicare summary notice",
        "MSN",
        "CHAMPVA",
        "TRICARE",
        # Coordination of benefits
        "coordination of benefits",
        "COB",
        "primary payer",
        "secondary payer",
        "primary insurance",
        "secondary insurance",
        # Pharmacy billing
        "NDC",
        "national drug code",
        "days supply",
        "day supply",
        "quantity dispensed",
        "qty dispensed",
        "refill",
        "refills remaining",
        "Rx number",
        "prescription number",
        "dispense date",
        "dispensed date",
        "pharmacy",
        "prescription",
        "pharmacist",
        # Medical bill audit
        "medical necessity",
        "not medically necessary",
        "medically necessary",
        "duplicate billing",
        "duplicate claim",
        "unbundling",
        "upcoding",
        "billing error",
        "overcoding",
        "review of charges",
        "charge review",
    ],
    patterns=[
        r"(?<!\d)[A-Z]\d{4}(?!\d)",             # HCPCS level II / CPT alpha-numeric
        r"\b\d{1,2}/\d{1,2}/\d{2,4}\b",         # date MM/DD/YYYY
        r"\b\d{4}-\d{2}-\d{2}\b",               # date YYYY-MM-DD
        r"\$\s?\d{1,3}(?:,\d{3})*(?:\.\d{2})?", # dollar amounts
        r"\bNPI[:\s#]*\d{10}\b",                 # NPI numbers
        r"\bRev(?:enue)?\s*(?:Code\s*)?\d{3,4}\b",  # UB-04 revenue codes
        r"\bNDC[:\s#]*\d{5}[-\s]\d{4}[-\s]\d{2}\b", # NDC drug codes
        r"\b[A-Z]\d{2}\.\d{1,4}\b",             # ICD-10 codes (e.g. M54.5, S13.4)
    ],
    weight=0.3,
)

CATEGORY_INJURY_LEGAL = KeywordCategory(
    name="INJURY_LEGAL",
    keywords=[
        # Accident / injury facts
        "accident",
        "motor vehicle accident",
        "MVA",
        "motor vehicle collision",
        "MVC",
        "collision",
        "bodily injury",
        "personal injury",
        "slip and fall",
        "trip and fall",
        "incident report",
        "witness statement",
        "property damage",
        # Workers compensation
        "workers compensation",
        "workers comp",
        "work comp",
        "first report of injury",
        "employer's first report",
        "FROI",
        "modified duty",
        "light duty",
        "work restrictions",
        "maximum medical improvement",
        "MMI",
        "DWC",
        "WCAB",
        "TTD",
        # Impairment / disability
        "impairment rating",
        "permanent impairment",
        "whole person impairment",
        "WPI",
        "permanent and stationary",
        "disability",
        "permanent disability",
        "temporary disability",
        # Auto insurance
        "personal injury protection",
        "PIP",
        "uninsured motorist",
        "underinsured motorist",
        "third party",
        "third-party claim",
        "liability",
        "subrogation",
        # Evaluations / examinations
        "independent medical examination",
        "IME",
        "defense medical examination",
        "defense IME",
        "independent medical evaluation",
        "qualified medical evaluator",
        "qualified medical examiner",
        "QME",
        "agreed medical evaluator",
        "agreed medical examiner",
        "AME",
        "panel QME",
        "panel physician",
        "FCE",
        "narrative report",
        # Legal process
        "affidavit",
        "declaration",
        "under penalty of perjury",
        "sworn statement",
        "notarized",
        "notary public",
        "petition",
        "objection to",
        "objections to",
        "interrogatories",
        "request for production",
        "expert witness",
        "deposition",
        "attorney",
        "law firm",
        # Legal parties / outcome
        "negligence",
        "causation",
        "claimant",
        "plaintiff",
        "defendant",
        "settlement",
        "demand letter",
        "lien",
        "medical lien",
        # Work status
        "work status",
        "restricted to",
        "restrict from",
    ],
    patterns=[
        r"\b\d{1,3}%\s+(?:whole\s+person\s+)?impairment\b",
        r"\b(?:claim|case|file)\s*(?:no|number|#)[:\s]*[\w\-]+\b",
        r"\bunder\s+penalty\s+of\s+perjury\b",
    ],
    weight=1.0,
)

CATEGORY_IMAGING = KeywordCategory(
    name="IMAGING",
    keywords=[
        "MRI",
        "magnetic resonance imaging",
        "CT scan",
        "computed tomography",
        "CAT scan",
        "X-ray",
        "radiograph",
        "radiography",
        "radiology",
        "radiologist",
        "radiology report",
        "imaging study",
        "ultrasound",
        "fluoroscopy",
        "bone scan",
        "DEXA",
        "myelogram",
        "discogram",
        "arthrogram",
        "EMG",
        "electromyography",
        "nerve conduction study",
        "NCS",
        "impression",
        "without contrast",
        "with contrast",
        "FLAIR",
        "flexion",
        "extension",
        "anterior",
        "posterior",
        "superior",
        "inferior",
        "lateral",
        "medial",
        "oblique",
        "axial",
        "sagittal",
        "coronal",
        "herniation",
        "disc herniation",
        "disc bulge",
        "stenosis",
        "spinal stenosis",
        "foraminal",
        "spondylosis",
        "fracture",
        "edema",
        "signal change",
        "hyperintense",
        "hypointense",
    ],
    patterns=[
        r"\b[CTLS]\d{1,2}[-–]\d{1,2}\b",
        r"\b[CTLS]\d{1,2}\b",
        r"\b(?:accession|study|exam)\s*(?:no|number|#)[:\s]*[\w\-]+\b",
        r"\bT[12][-\s]weighted\b",
    ],
    weight=1.2,
)

CATEGORY_BEHAVIORAL_HEALTH = KeywordCategory(
    name="BEHAVIORAL_HEALTH",
    keywords=[
        "psychiatry",
        "psychiatrist",
        "psychology",
        "psychologist",
        "psychotherapy",
        "counseling",
        "counselor",
        "mental health",
        "behavioral health",
        "depression",
        "anxiety",
        "PTSD",
        "post-traumatic stress",
        "post traumatic stress",
        "panic disorder",
        "OCD",
        "obsessive-compulsive",
        "bipolar",
        "mood disorder",
        "adjustment disorder",
        "GAD",
        "generalized anxiety",
        "anxious",
        "depress",
        "depressed",
        "major depressive disorder",
        "MDD",
        "cognitive behavioral therapy",
        "CBT",
        "EMDR",
        "DBT",
        "dialectical behavioral",
        "medication management",
        "antidepressant",
        "SSRI",
        "SNRI",
        "antipsychotic",
        "anxiolytic",
        "benzodiazepine",
        "PHQ-9",
        "GAD-7",
        "psychiatric evaluation",
        "mental status examination",
        "MSE",
        "suicidal ideation",
        "homicidal ideation",
        "session",
        "progress note",
        "cognitive",
        "neurocognitive",
    ],
    patterns=[
        r"\b[FZ]\d{2}(?:\.\d{1,4})?\b",
        r"(?<!\d)90[0-9]{3}(?!\d)",
    ],
    weight=1.5,
)

CATEGORY_VOCATIONAL = KeywordCategory(
    name="VOCATIONAL",
    keywords=[
        # Work history
        "work history",
        "employment history",
        "job history",
        "employment record",
        "prior employment",
        "previous employment",
        "occupational history",
        "vocational history",
        "employer",
        "employment",
        # Earnings / wages
        "wage",
        "salary",
        "earning",
        "income",
        "compensation",
        "lost wage",
        "wage loss",
        "earning capacity",
        "loss of earning capacity",
        "lost income",
        "annual income",
        "hourly wage",
        "hourly rate",
        "weekly wage",
        "monthly income",
        "IRS",
        "W2",
        "1099",
        "social security",
        "SSA",
        "bank statement",
        "paystub",
        "deposit",
        # Job descriptions / duties
        "job description",
        "job duty",
        "job duties",
        "job demand",
        "essential function",
        "physical demand",
        "occupational duty",
        "occupational duties",
        "job title",
        "occupation",
        # Physical work restrictions / capacity
        "work capacity",
        "work tolerance",
        "sedentary",
        "sedentary work",
        "light work",
        "medium work",
        "heavy work",
        "lifting limit",
        "lifting restriction",
        "return to work",
        "RTW",
        "unable to work",
        "work ability",
        "full duty",
        "transitional work",
        "job placement",
        "vocational rehabilitation",
        "vocational assessment",
        "vocational evaluation",
        "transferable skill",
        "labor market",
    ],
    patterns=[
        r"\blift(?:ing)?\s+(?:up\s+to\s+)?\d+\s*(?:lbs?|pounds?)\b",
        r"\b(?:stand|sit|walk)\s+(?:up\s+to\s+)?\d+\s*(?:hours?|hrs?)\b",
    ],
    weight=2.0,
)

CATEGORY_DOCUMENT_TYPE = KeywordCategory(
    name="DOCUMENT_TYPE",
    keywords=[
        # Hospital / ER records
        "discharge note",
        "history and physical",
        "history & physical",
        "H&P",
        "consultation note",
        "consult note",
        "consultation report",
        "physician note",
        "attending note",
        "attending physician note",
        "admission note",
        "admission history",
        "admitting note",
        "emergency department note",
        "triage note",
        "intake note",
        "operative note",
        "procedure note",
        "surgical note",
        # Therapy / rehabilitation
        "initial evaluation",
        "re-evaluation",
        # Imaging
        "imaging report",
        # Behavioral health
        "psychotherapy note",
        "initial psychiatric",
        "psychological evaluation",
        # Legal / IME
        "medical legal report",
        # Therapy subtype — intake / initial encounter
        "initial assessment",
        "intake assessment",
        "initial session",
        "first session",
        "first visit",
        "initial visit",
        "evaluation and management",
        # Therapy subtype — discharge / termination
        "termination note",
        "termination summary",
        "termination session",
        "final session",
        "final visit",
        "final note",
        "treatment termination",
        "discharge plan",
        # Therapy subtype — progress notes
        "session note",
        "treatment note",
        "SOAP note",
    ],
    patterns=[
        r"\b(?:discharge|admission|progress|consultation|attending|physician|operative|procedure|triage|intake|initial|termination)\s+(?:summary|note|report|history|evaluation)\b",
    ],
    weight=1.5,
)

DEFAULT_CATEGORIES: list[KeywordCategory] = [
    CATEGORY_THERAPY,
    CATEGORY_MEDICAL_TREATMENT,
    CATEGORY_BILLING,
    CATEGORY_INJURY_LEGAL,
    CATEGORY_IMAGING,
    CATEGORY_BEHAVIORAL_HEALTH,
    CATEGORY_VOCATIONAL,
    CATEGORY_DOCUMENT_TYPE,
]

# Categories that indicate genuine clinical content. Used by the require_anchor filter
# to exclude pages that only matched administrative categories (Billing).
CLINICAL_ANCHOR_CATEGORIES: frozenset[str] = frozenset({
    "THERAPY",
    "MEDICAL_TREATMENT",
    "INJURY_LEGAL",
    "IMAGING",
    "BEHAVIORAL_HEALTH",
    "VOCATIONAL",
    "DOCUMENT_TYPE",
})

# Bills-pass parameters — used internally by scan_directory() for the second pass.
_BILLS_MIN_HITS: float = 0.3
_BILLS_REQUIRE_CATEGORIES: frozenset[str] = frozenset({"BILLING", "INJURY_LEGAL"})


def highest_weight_category(
    categories_matched: list[str],
    categories: list["KeywordCategory"],
) -> str | None:
    """Return the name of the matched category with the highest weight.

    When weights tie the category that appears earliest in *categories* wins,
    giving a stable, deterministic result.  Returns None if categories_matched
    is empty or none of its names appear in *categories*.
    """
    cat_weight: dict[str, float] = {c.name: c.weight for c in categories}
    best: str | None = None
    best_w = -1.0
    for name in categories_matched:
        w = cat_weight.get(name, 0.0)
        if w > best_w:
            best_w = w
            best = name
    return best
